apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-ha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codis-ha
    spec:
      imagePullSecrets:
      - name: your-registry
      containers:
      - name: codis-ha
        image: codis-image
        imagePullPolicy: IfNotPresent
        command: ["codis-ha"]
        args: ["-l","log/$(POD_NAME).log","--interval","5","--dashboard=codis-dashboard:18080"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name 
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "0.1"
            memory: 0.1Gi
