apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codis-proxy
    spec:
      imagePullSecrets:
      - name: cn-registry
      containers:
      - name: codis-proxy
        image: codis-image3
        imagePullPolicy: Never
        command: ["codis-proxy"]
        args: ["-l","log/proxy.log","-c","$(CODIS_PATH)/config/proxy.toml","--host-admin","$(POD_IP):11080","--host-proxy","$(POD_IP):19000","--zookeeper","$(ZK_ADDR)","--pidfile","log/proxy.pid"]
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "codis-admin --dashboard=${DASHBOARD_ADDR} --remove-proxy --addr=${POD_IP}:11080 1>/dev/null 2>&1"]
        env:
        - name: CODIS_PATH
          value: "/gopath/src/github.com/CodisLabs/codis"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ZK_ADDR
          value: "zookeeper:2181"
        - name: DASHBOARD_ADDR
          value: "codis-dashboard:18080"
        ports:
        - containerPort: 11080
          name: proxy
        - containerPort: 19000
          name: admin
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.1"
            memory: 0.1Gi
