apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-fe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codis-fe
    spec:
      imagePullSecrets:
      - name: cn-registry
      containers:
      - name: codis-fe
        image: codis-image:k8s
        imagePullPolicy: IfNotPresent
        command: ["codis-fe"]
        args: ["-l","log/fe.log","--zookeeper","zookeeper:2181","--listen=$(POD_IP):8080","--assets=$(CODIS_PATH)/bin/assets"]
        env:
        - name: CODIS_PATH
          value: "/gopath/src/github.com/CodisLabs/codis"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
          name: fe
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.1"
            memory: 0.1Gi
